#!/bin/bash

section=${1};
kind=${2};
width=${3};

for (( resize = 100; resize <= 300; resize += 1 ))
do
	for (( value = 0; value <= 50; value += 5 ))
	do
		printf "%d %2d: " ${resize} ${threshold};

		optCmd="go run utils/genConvert.go -${section}-resize ${resize} -${section}-${kind} ${value} -base ${width} -output ${width}";
		testCmd="go test -short -parallel 4 -test.run ${width}x ./ocr/... -${section}";

		start=$(date +%s.%N)
		eval $optCmd;
		testReturn=$(eval $testCmd);
		end=$(date +%s.%N)

		numErrors=$(echo "${testReturn}" | grep -c Expected)
		printf "%3d error(s) in %.4fs\n" ${numErrors} $(echo "${end} - ${start}" | bc -l);

		if [ ${numErrors} -eq 0 ]
		then
			echo ${optCmd};
			exit 0;
			#echo ${testCmd};
		fi
	done
done
