#!/bin/bash

section=${1};
width=${2};
resize=${3};
level=${4};

go run \
	utils/genConvert.go \
	-${section}-resize ${resize} \
	-${section}-level ${level} \
	-base ${width} \
	-output ${width} \
	&&
	go test \
	-short \
	-parallel 4 \
	-test.run ${width}x \
	./ocr/... \
	-${section} \
